# 所有环境通用的配置，放在这里
spring:
  profiles:
    active: dev
  # 热部署
  devtools:
    livereload:
      enabled: true
#mybaits-plus配置
mybatis-plus:
  mapperLocations: classpath:mapper/**/*.xml
  global-config:
    banner: false
  type-aliases-package: com.company.project.**.entity
