# 所有环境通用的配置，放在这里
spring:
  profiles:
    active: dev


# mybaits-plus配置
mybatis-plus:
  mapperLocations: classpath:mapper/**/*.xml
  global-config:
    banner: false
  type-aliases-package: com.company.project.**.entity
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #控制台打印完整带参数SQL语句

# 配置日志输出的级别
logging:
  level:
    com.company.project: debug
    org.springframework.cache: trace
